# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: godep-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: godep-app
  template:
    metadata:
      labels:
        app: godep-app
    spec:
      containers:
        - name: godep-app
          image: godep-app:latest
          ports:
            - containerPort: 8080
